# Assignment 01
## 학번 : 2021305082
## 성명 : 최재륜
### 제출일 : 2026.03.16

# Part 1 Numpy

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 예시)
### 설명 : reshape(m,n) 메소드는 기존 array를 m행 n열로 변환해 반환한다. 

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### 설명 : reshape()는 배열의 모양(구조)을 바꾸는 함수이다
### reshape(2,3,2)는 3차원 배열로 2개의 묶음에 각 묶음에 3행 2열로 변환된다

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
sum_value = np.sum(arr)
mean_value= np.mean(arr)
print(sum_value)
print(mean_value)

78
6.5


### 설명 : sum()은 모든 원소의 합, mean()은 평균값을 계산한다. 따라서 arr의 모든 원소의 합과 평균을 출력한다.

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
prod_value = np.prod(arr)
cum_value= np.cumsum(arr)
print(prod_value)
print(cum_value)

479001600
[ 1  3  6 10 15 21 28 36 45 55 66 78]


### 설명 : prod()는 모든 원소를 곱한 값, cumsum()은 누적합으로 앞에서부터 계속 더한 값이다.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


### 설명 : for x in arr에서 arr은 2차원 배열이기 때문에 x는 행 단위로 반복해서 1번째 반복으로 [1 2 3]을 하고 2번째 반복으로 [4 5 6]이 나온다.

In [6]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


### 설명 : arr은 1차원 배열이고 x는 원소 하나씩 반복한다. 따라서 출력은 각 원소를 하나씩 출력한다.

In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


### 설명 : stack()은 배열을 새 차원으로 합치는 함수이고 axis=1은 열 방향으로 합친다. 2개의 1차원 배열을 열 방향으로 합치는 다음과 같은 출력이 나온다.
### axis=0은 열로 합친다.

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


### 설명 : hstack()은 배열을 가로 방향(열)으로 이어붙인다. arr1에 arr2를 이어 붙인다.

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


### 설명 : vstack()은 세로 방향(행)으로 쌓는다. arr은 2차원 배열이 된다.

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


### 설명 : array_split(arr,3)은 arr 배열을 3개로 나눈다. 그리고 각 조각들을 출력한다.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)


### 설명 : where()은 조건을 만족하는 원소의 인덱스 위치를 찾는 것으로 arr=4가 만족하는 위치들이 출력된다.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)


(array([1, 3, 5, 7], dtype=int64),)


### 설명 : arr%2==0은 arr을 2로 나누었을 때 나머지가 0인, 즉 짝수를 찾는 것이다. where을 통해 짝수 값을 가진 인덱스들을 반환한다.

In [13]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


### 설명 : sort()는 배열을 오름차순으로 정렬시킨다.

In [14]:
arr = np.array([True, False, True])
print(np.sort(arr))


[False  True  True]


### 설명 : False는 0, True는 1로 취급한다. 따라서 sort로 정렬하면 False부터 나온다.

In [15]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


설명 : 2차원 배열을 sort로 정렬할 때 기본적으로 행 기준으로 정렬한다.

즉, 각 행을 따로 정렬한다.

In [16]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)


[41 43]


#### 설명 : arr의 인덱스와 x의 인덱스를 비교해서 True인 위치의 값만 가져온다.

In [17]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
 
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


### 설명 : filter_arr은 arr 배열 원소를 하나씩 검사하는데 만약 42보다 크다면 True, 아니라면 False의 값을 가진다.
### newarr은 arr을 filter_arr 통해 True 위치만 필터링한다.

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


### 설명 : arr 배열 중에서 짝수이면 True, 홀수이면 False의 값을 갖고 filter_arr에 추가한다.
### arr을 filter_arr로 True만 필터링하여 newarr을 출력한다.
### 즉 짝수를 출력하는 프로그램이다.

In [19]:
from numpy import random
x = random.randint(100)
print(x)

59


### 설명 : 난수 기능을 사용하기 위해 random을 import한다.
### randint(100)은 0부터 99 사이 정수 중 랜덤으로 하나를 생성한다. 매번 다른 값이 나오게 된다.

In [20]:
from numpy import random
x = random.rand(5)
print(x)

[0.91124871 0.53497185 0.53667554 0.25454859 0.01600453]


### 설명 : random.rand(5)는 0부터 1사이에 랜덤 실수를 5개 생성한다.

In [21]:
from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)


[[9 7 5 5 5]
 [7 3 7 5 7]
 [9 3 5 5 5]]


#### 설명 : choice(리스트, size=(행,열))이다. 33행 5열 크기의 배열을 만들고 3,5,7,9 중 하나를 랜덤으로 넣는다.

In [22]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[3 7 5 3 5 3 5 5 7 3 7 5 3 5 5 5 7 5 5 7 5 3 7 5 7 7 5 7 5 7 7 5 7 7 5 3 7
 7 5 7 7 5 7 3 7 7 5 7 3 7 7 3 3 7 5 7 5 7 7 7 7 7 7 5 7 5 7 7 5 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 5 7 5 7 5 5 7 7 5 7 7]


##### 설명 : p=확률이다. 각 원소들의 확률을 정하고 100개를 생성한다. 7의 확률이 가장 높아서 가장 많이 나왔으면 0.0인 9는 나오지 않는다.

In [23]:
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 7 3 7]
 [7 7 7 7 7]
 [5 7 7 3 3]]


##### 설명 : 3행 5열의 배열에 3,5,7,9를 각각의 확률에 따라 뽑힌다.

In [24]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)


[1 4 3 5 2]


random.shuffle()은 배열의 순서를 랜덤으로 섞는다.

실행할 때마다 달라지게 되고 원본 배열을 직접 바꾼다.

In [25]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[5 3 2 1 4]


설명 : permutation()은 배열을 랜덤으로 섞은 새 배열을 생성한다.

shuffle()과 다른 점은 원본은 그대로 있고, 새 배열을 반환한다.

In [26]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


#### 설명 : add(m,n)는 m과 n의 같은 위치 원소끼리 더한다

In [27]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


##### 설명 : subtract(m,n)은 m과 n의 같은 위치 원소끼리 뺸다.

In [28]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)


[ 200  420  660  920 1200 1500]


##### 설명 : subtract(m,n)은 m과 n의 같은 위치 원소끼리 곱한다.

In [29]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)


[ 3.33333333  4.          3.          5.         25.          1.81818182]


##### 설명 : subtract(m,n)은 m과 n의 같은 위치 원소끼리 나눈다. 결과는 보통 실수(float)로 나오게 된다.

In [30]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)


[      1000    3200000  729000000 -520093696       2500          0]


### 설명 : power(m,n)은 m과 n의 같은 위치 원소끼리 거듭제곱한다. m^n이다.

In [31]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result_dot_product = np.dot(a, b)
print(result_dot_product)

32


#### 설명 : dot()은 벡터의 내적이다. 같은 위치 원소를 곱한 후 전부 더한다.

# Part 2 Pandas

In [32]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'],
'Height (inches)': [65, 72, 68]}
df = pd.DataFrame(data)
print(df)

      Name  Height (inches)
0    Alice               65
1      Bob               72
2  Charlie               68


#### 설명 : data라는 딕셔너리를 DataFrame(표 형태 데이터)로 변환하고 출력한다.

In [33]:
tallest = df[df['Height (inches)'] == df['Height (inches)'].max()]
print(tallest)

  Name  Height (inches)
1  Bob               72


##### 설명 : df['Height (inches)'].max()로 최댓값을 72를 찾는다.
##### df['Height (inches)'] == 72인 값만 True로 바꾼다.
##### df[조건]으로 True인 행만 남겨서 72인 행만 출력된다.

In [34]:
import pandas as pd
data = {
'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
'Population (millions)': [8.4, 3.9, 2.7, 2.3, 1.8],
'Avg Temperature (F)': [62, 70, 54, 68, 76]
}
cities_df = pd.DataFrame(data)

selected_columns = cities_df[['City', 'Avg Temperature (F)']]
print(selected_columns)

          City  Avg Temperature (F)
0     New York                   62
1  Los Angeles                   70
2      Chicago                   54
3      Houston                   68
4      Phoenix                   76


#### 설명: cities_df[['City', 'Avg Temperature (F)']]를 통해 City 열과 Avg Temperature (F)열만 선택하고 출력한다.
#### df[['컬럼1','컬럼2']]은 특정 열만 선택한다.

In [35]:
large_cities = cities_df[cities_df['Population (millions)'] > 3]
print(large_cities)

          City  Population (millions)  Avg Temperature (F)
0     New York                    8.4                   62
1  Los Angeles                    3.9                   70


##### 설명 : cities_df['Population (millions)'] > 3 로 인구가 3백만 이상인지 검사하고 맞으면 True, 아니면 False의 값을 넣고 cities_df[조건]으로 True인 행만 선택하고 출력한다.